version: 2

updates:
  - package-ecosystem: "deno"
    directories:
      - "/backend"
      - "/database"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
