import { Buffer } from "node:buffer";

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[] ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type AvatarOrigin =
  | "licence"
  | "other"
  | "own_work"
  | "permission"
  | "public_domain";

export type BlindDateAgain = "maybe" | "no" | "yes";

export type BlindDateApplicationStatus =
  | "declined"
  | "expired"
  | "matched"
  | "pending"
  | "withdrawn";

export type BlindDatePostLength = "long" | "medium" | "short";

export type BlindDateVerdict = "no" | "partly" | "yes";

export type BlindDateWritingStyle = "asterisk" | "prose";

export type ForumVisibility =
  | "administration"
  | "everyone"
  | "members"
  | "moderation";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type NotificationType =
  | "blind_date_ended"
  | "blind_date_matched"
  | "blind_date_reveal_requested"
  | "invitation_accepted"
  | "invited_to_chat_group"
  | "invited_to_writing_group"
  | "new_writing_post"
  | "new_writing_thread"
  | "role_changed_in_writing_group"
  | "visibility_changed_in_writing_group";

export type PlatformRole = "administrator" | "moderator";

export type ProfileQuestionKind = "choice" | "text";

export type ReportCategory =
  | "harassment"
  | "hate"
  | "illegal_content"
  | "legal_issue"
  | "missing_content_warning"
  | "other"
  | "plagiarism"
  | "self_harm"
  | "sexual_content"
  | "spam"
  | "violence";

export type ReportOutcome =
  | "account_banned"
  | "content_removed"
  | "content_warning_added"
  | "duplicate"
  | "insufficient_information"
  | "no_violation"
  | "other"
  | "target_gone"
  | "warning_given";

export type ReportStatus = "closed" | "in_progress" | "open";

export type ReportTargetType =
  | "chat_group"
  | "chat_message"
  | "forum_post"
  | "story_idea"
  | "user"
  | "writing_group"
  | "writing_post"
  | "writing_thread";

export type StoryContentWarning =
  | "abuse"
  | "animal_cruelty"
  | "death"
  | "discrimination"
  | "eating_disorder"
  | "gore"
  | "grief"
  | "mental_illness"
  | "pregnancy_loss"
  | "self_harm"
  | "sexual_content"
  | "sexual_violence"
  | "substance_abuse"
  | "suicide"
  | "violence"
  | "war";

export type StoryGenre =
  | "action"
  | "adventure"
  | "comedy"
  | "crime"
  | "drama"
  | "fantasy"
  | "historical"
  | "horror"
  | "literary"
  | "mystery"
  | "retelling"
  | "romance"
  | "science_fiction"
  | "slice_of_life"
  | "thriller"
  | "western";

export type StoryIdeaPartySize = "group" | "one_on_one";

export type StoryIdeaStatus = "closed" | "open";

export type StoryLanguage = "english" | "german";

export type StoryPerspective =
  | "first_person"
  | "mixed"
  | "second_person"
  | "third_person_limited"
  | "third_person_omniscient";

export type StorySubgenre =
  | "ancient_world"
  | "body_horror"
  | "classic_western"
  | "closed_door_romance"
  | "comedy_romance"
  | "coming_of_age"
  | "contemporary_romance"
  | "cosy_mystery"
  | "cosy_romance"
  | "creature_horror"
  | "cyberpunk"
  | "dark_comedy"
  | "dark_fantasy"
  | "detective"
  | "doll_horror"
  | "dystopian"
  | "early_modern"
  | "erotic_romance"
  | "everyday_life"
  | "experimental"
  | "exploration"
  | "fairy_tale"
  | "family_drama"
  | "family_life"
  | "first_contact"
  | "forbidden_romance"
  | "gothic_horror"
  | "heist"
  | "high_fantasy"
  | "historical_romance"
  | "intrigue"
  | "legal_thriller"
  | "magical_realism"
  | "martial_arts"
  | "medieval"
  | "military_action"
  | "mythic_fantasy"
  | "noir"
  | "organised_crime"
  | "paranormal_fantasy"
  | "parody"
  | "police_procedural"
  | "portal_fantasy"
  | "post_apocalyptic"
  | "psychological_horror"
  | "psychological_thriller"
  | "quest"
  | "retold_book"
  | "retold_manga"
  | "retold_movie"
  | "retold_myth"
  | "retold_saga"
  | "romantic_comedy"
  | "romantic_fantasy"
  | "satire"
  | "school_life"
  | "space_opera"
  | "spy_action"
  | "spy_thriller"
  | "superhero"
  | "supernatural_horror"
  | "survival_adventure"
  | "survival_thriller"
  | "time_travel"
  | "time_travel_fantasy"
  | "tragedy"
  | "treasure_hunt"
  | "twentieth_century"
  | "university_life"
  | "urban_fantasy"
  | "vacation"
  | "victorian"
  | "weird_western"
  | "whodunit"
  | "workplace"
  | "world_war";

export type StoryTense = "mixed" | "past" | "present";

export type StoryTrope =
  | "amnesia"
  | "chosen_one"
  | "court_intrigue"
  | "enemies_to_lovers"
  | "ensemble_cast"
  | "epistolary"
  | "fake_relationship"
  | "forbidden_love"
  | "forced_proximity"
  | "found_family"
  | "friends_to_lovers"
  | "friends_with_benefits"
  | "grumpy_and_sunshine"
  | "heist_crew"
  | "hero_to_villain"
  | "hidden_identity"
  | "locked_room"
  | "love_triangle"
  | "mentor_and_student"
  | "morally_grey_protagonist"
  | "multiple_timelines"
  | "quest_for_an_artefact"
  | "redemption_arc"
  | "rivals"
  | "road_trip"
  | "second_chance"
  | "secret_heritage"
  | "slow_burn"
  | "time_loop"
  | "unreliable_narrator"
  | "villain_to_hero";

export type StrikeAction = "deletion" | "suspension" | "warning";

export type StrikeSeverity = "acceptable" | "borderline" | "severe";

export type UserInChatGroupStatus = "invited" | "joined";

export type UserInWritingGroupRole = "administrator" | "reader" | "writer";

export type UserInWritingGroupStatus = "invited" | "joined";

export type UserTokenPurpose =
  | "account_deletion"
  | "email_address_change"
  | "email_address_verification"
  | "password_reset";

export type WritingGroupStoryStatus = "finished" | "planning" | "writing";

export type WritingGroupVisibility = "private" | "public";

export interface ActivityWindow {
  userId: string;
  windowStart: string;
}

export interface BannedIp {
  bannedAt: Generated<string>;
  bannedBy: string | null;
  ipAddress: string;
  reason: string;
}

export interface BlindDateApplication {
  createdAt: Generated<string>;
  decidedAt: string | null;
  decidedBy: string | null;
  decisionNote: string | null;
  id: Generated<string>;
  note: string | null;
  offerId: string | null;
  pairing: string;
  plotTitle: string;
  postLength: BlindDatePostLength;
  roleGender: string;
  status: Generated<BlindDateApplicationStatus>;
  userId: string;
  writingStyle: BlindDateWritingStyle;
}

export interface BlindDateExclusion {
  addedAt: Generated<string>;
  addedBy: string | null;
  reason: string;
  userId: string;
}

export interface BlindDateFeedback {
  again: BlindDateAgain | null;
  createdAt: Generated<string>;
  id: Generated<string>;
  note: string | null;
  pairId: string;
  userId: string;
  worked: BlindDateVerdict | null;
}

export interface BlindDateNameSuspicion {
  confirmed: boolean | null;
  createdAt: Generated<string>;
  id: Generated<string>;
  pairId: string;
  reportId: string;
  resolvedAt: string | null;
  resolvedBy: string | null;
  suspectedId: string;
  writingPostId: string | null;
}

export interface BlindDateOffer {
  closedAt: string | null;
  closesAt: string | null;
  createdAt: Generated<string>;
  createdBy: string | null;
  description: string;
  id: Generated<string>;
  roles: Generated<string[]>;
  title: string;
}

export interface BlindDatePair {
  endedAt: string | null;
  endedBy: string | null;
  endedReason: string | null;
  exchangeThreadId: string | null;
  id: Generated<string>;
  matchedAt: Generated<string>;
  matchedBy: string | null;
  revealedAt: string | null;
  rpgThreadId: string | null;
  writingGroupId: string;
}

export interface BlindDatePartner {
  applicationId: string | null;
  isActive: Generated<boolean>;
  pairId: string;
  userId: string;
  wantsRevealAt: string | null;
}

export interface BlockedEmailDomain {
  addedAt: Generated<string>;
  addedBy: string | null;
  domain: string;
  note: string | null;
}

export interface BlockedWord {
  addedAt: Generated<string>;
  addedBy: string | null;
  note: string | null;
  word: string;
}

export interface ChatGroup {
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  lastActivityAt: Generated<string>;
  title: string;
}

export interface ChatMessage {
  chatGroupId: string;
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  text: string;
}

export interface CustomPage {
  body: string;
  createdAt: Generated<string>;
  isPublic: Generated<boolean>;
  lastEditedBy: string | null;
  slug: string;
  title: string;
  updatedAt: Generated<string>;
}

export interface Favourite {
  chatGroupId: string | null;
  createdAt: Generated<string>;
  forumPostId: string | null;
  id: Generated<string>;
  storyIdeaId: string | null;
  userId: string;
  writingGroupId: string | null;
  writingPostId: string | null;
  writingThreadId: string | null;
}

export interface ForumCategory {
  createdAt: Generated<string>;
  id: Generated<string>;
  position: Generated<number>;
  title: string;
}

export interface ForumPost {
  createdAt: Generated<string>;
  createdBy: string | null;
  document: unknown;
  editedAt: string | null;
  editedBy: string | null;
  forumThreadId: string;
  id: Generated<string>;
  text: string;
}

export interface ForumThread {
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  lastActivityAt: Generated<string>;
  subForumId: string;
  title: string;
  visibility: ForumVisibility | null;
}

export interface Notification {
  actorId: string | null;
  chatGroupId: string | null;
  createdAt: Generated<string>;
  id: Generated<string>;
  occurredAt: Generated<string>;
  readAt: string | null;
  recipientId: string;
  type: NotificationType;
  writingGroupId: string | null;
  writingPostId: string | null;
  writingThreadId: string | null;
}

export interface ProfileAnswer {
  answerText: string | null;
  optionId: string | null;
  questionId: string;
  userId: string;
}

export interface ProfileQuestion {
  id: Generated<string>;
  kind: ProfileQuestionKind;
  position: Generated<number>;
  prompt: string;
  section: string;
}

export interface ProfileQuestionOption {
  id: Generated<string>;
  label: string;
  position: Generated<number>;
  questionId: string;
}

export interface Report {
  category: ReportCategory;
  closedAt: string | null;
  closingNote: string | null;
  closingOutcome: ReportOutcome | null;
  createdAt: Generated<string>;
  id: Generated<string>;
  inProgressAt: string | null;
  operatorId: string | null;
  reason: string;
  reportedAuthorId: string | null;
  reportedChatGroupId: string | null;
  reportedChatMessageId: string | null;
  reportedForumPostId: string | null;
  reportedStoryIdeaId: string | null;
  reportedUserId: string | null;
  reportedWritingGroupId: string | null;
  reportedWritingPostId: string | null;
  reportedWritingThreadId: string | null;
  reporterId: string | null;
  status: Generated<ReportStatus>;
  targetExcerpt: string;
  targetType: ReportTargetType;
}

export interface StatusUpdate {
  body: string;
  createdAt: Generated<string>;
  createdBy: string;
  id: Generated<string>;
}

export interface StatusUpdateComment {
  body: string;
  createdAt: Generated<string>;
  createdBy: string;
  id: Generated<string>;
  statusUpdateId: string;
}

export interface StoryIdea {
  contentWarnings: Generated<ArrayType<StoryContentWarning>>;
  createdAt: Generated<string>;
  createdBy: string;
  genres: Generated<ArrayType<StoryGenre>>;
  id: Generated<string>;
  language: Generated<StoryLanguage>;
  lookingFor: string | null;
  partySize: StoryIdeaPartySize | null;
  perspective: StoryPerspective | null;
  status: Generated<StoryIdeaStatus>;
  storySettings: string | null;
  storyThemes: string | null;
  subgenres: Generated<ArrayType<StorySubgenre>>;
  subtitle: string | null;
  synopsis: string;
  teaser: string;
  tense: StoryTense | null;
  title: string;
  tropes: Generated<ArrayType<StoryTrope>>;
}

export interface StoryIdeaReader {
  createdAt: Generated<string>;
  storyIdeaId: string;
  userId: string;
}

export interface Strike {
  action: StrikeAction;
  id: Generated<string>;
  issuedAt: Generated<string>;
  issuedBy: string | null;
  reason: string;
  severity: StrikeSeverity;
  suspendedUntil: string | null;
  userId: string;
}

export interface SubForum {
  categoryId: string;
  createdAt: Generated<string>;
  description: string;
  id: Generated<string>;
  position: Generated<number>;
  title: string;
  visibility: Generated<ForumVisibility>;
}

export interface User {
  aboutMe: string | null;
  bannedAt: string | null;
  bannedBy: string | null;
  banReason: string | null;
  coWriterExpectations: string | null;
  createdAt: Generated<string>;
  emailAddress: string;
  emailAddressVerifiedAt: string | null;
  genres: string | null;
  hashedPassword: string;
  id: Generated<string>;
  invitedBy: string | null;
  isPrimordialAdmin: Generated<boolean>;
  platformRole: PlatformRole | null;
  postLength: string | null;
  suspendedUntil: string | null;
  suspensionReason: string | null;
  updatedAt: Generated<string>;
  username: string;
  writingBoundaries: string | null;
  writingFrequency: string | null;
  writingStyle: string | null;
}

export interface UserAvatar {
  createdAt: Generated<string>;
  credit: string | null;
  fileId: Generated<string>;
  origin: AvatarOrigin;
  userId: string;
}

export interface UserBlock {
  blockedId: string;
  blockerId: string;
  createdAt: Generated<string>;
}

export interface UserInChatGroup {
  chatGroupId: string;
  createdAt: Generated<string>;
  invitedAt: string | null;
  joinedAt: string | null;
  lastReadAt: string | null;
  status: UserInChatGroupStatus;
  userId: string;
}

export interface UserInWritingGroup {
  createdAt: Generated<string>;
  invitedAt: string | null;
  invitedBy: string | null;
  joinedAt: string | null;
  role: UserInWritingGroupRole;
  status: UserInWritingGroupStatus;
  userId: string;
  writingGroupId: string;
}

export interface UserSession {
  createdAt: Generated<string>;
  expiresAt: string;
  hashedToken: Buffer;
  id: Generated<string>;
  ipAddress: string | null;
  updatedAt: Generated<string>;
  userAgent: string | null;
  userId: string;
}

export interface UserToken {
  consumedAt: string | null;
  createdAt: Generated<string>;
  expiresAt: string;
  hashedToken: Buffer;
  id: Generated<string>;
  newEmailAddress: string | null;
  purpose: UserTokenPurpose;
  userId: string;
}

export interface WatchlistEntry {
  addedAt: Generated<string>;
  addedBy: string | null;
  note: string;
  userId: string;
}

export interface WritingGroup {
  authorsArePseudonymous: Generated<boolean>;
  contentWarnings: Generated<ArrayType<StoryContentWarning>>;
  createdAt: Generated<string>;
  createdBy: string | null;
  genres: Generated<ArrayType<StoryGenre>>;
  id: Generated<string>;
  language: Generated<StoryLanguage>;
  lastActivityAt: Generated<string>;
  perspective: StoryPerspective | null;
  storySettings: string | null;
  storyStatus: Generated<WritingGroupStoryStatus>;
  storyThemes: string | null;
  subgenres: Generated<ArrayType<StorySubgenre>>;
  subtitle: string | null;
  synopsis: string;
  tense: StoryTense | null;
  title: string;
  tropes: Generated<ArrayType<StoryTrope>>;
  visibility: Generated<WritingGroupVisibility>;
}

export interface WritingGroupNextStep {
  completedAt: string | null;
  completedBy: string | null;
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  text: string;
  writingGroupId: string;
}

export interface WritingPost {
  createdAt: Generated<string>;
  createdBy: string | null;
  document: unknown;
  editedAt: string | null;
  editedBy: string | null;
  id: Generated<string>;
  isDraft: boolean;
  text: string;
  writingThreadId: string;
}

export interface WritingThread {
  createdAt: Generated<string>;
  createdBy: string | null;
  id: Generated<string>;
  lastActivityAt: Generated<string>;
  title: string;
  writingGroupId: string;
}

export interface DB {
  activityWindow: ActivityWindow;
  bannedIp: BannedIp;
  blindDateApplication: BlindDateApplication;
  blindDateExclusion: BlindDateExclusion;
  blindDateFeedback: BlindDateFeedback;
  blindDateNameSuspicion: BlindDateNameSuspicion;
  blindDateOffer: BlindDateOffer;
  blindDatePair: BlindDatePair;
  blindDatePartner: BlindDatePartner;
  blockedEmailDomain: BlockedEmailDomain;
  blockedWord: BlockedWord;
  chatGroup: ChatGroup;
  chatMessage: ChatMessage;
  customPage: CustomPage;
  favourite: Favourite;
  forumCategory: ForumCategory;
  forumPost: ForumPost;
  forumThread: ForumThread;
  notification: Notification;
  profileAnswer: ProfileAnswer;
  profileQuestion: ProfileQuestion;
  profileQuestionOption: ProfileQuestionOption;
  report: Report;
  statusUpdate: StatusUpdate;
  statusUpdateComment: StatusUpdateComment;
  storyIdea: StoryIdea;
  storyIdeaReader: StoryIdeaReader;
  strike: Strike;
  subForum: SubForum;
  user: User;
  userAvatar: UserAvatar;
  userBlock: UserBlock;
  userInChatGroup: UserInChatGroup;
  userInWritingGroup: UserInWritingGroup;
  userSession: UserSession;
  userToken: UserToken;
  watchlistEntry: WatchlistEntry;
  writingGroup: WritingGroup;
  writingGroupNextStep: WritingGroupNextStep;
  writingPost: WritingPost;
  writingThread: WritingThread;
}
import * as z from "zod";

const int32 = z.int().min(-2147483648).max(2147483647);

export const WRITING_GROUP_VISIBILITIES = ["private", "public"] as const;
export const WRITING_GROUP_VISIBILITY_SCHEMA = z.enum(
  WRITING_GROUP_VISIBILITIES,
);

export const STORY_LANGUAGES = ["english", "german"] as const;
export const STORY_LANGUAGE_SCHEMA = z.enum(STORY_LANGUAGES);

export const WRITING_GROUP_STORY_STATUSES = [
  "finished",
  "planning",
  "writing",
] as const;
export const WRITING_GROUP_STORY_STATUS_SCHEMA = z.enum(
  WRITING_GROUP_STORY_STATUSES,
);

export const STORY_GENRES = [
  "action",
  "adventure",
  "comedy",
  "crime",
  "drama",
  "fantasy",
  "historical",
  "horror",
  "literary",
  "mystery",
  "retelling",
  "romance",
  "science_fiction",
  "slice_of_life",
  "thriller",
  "western",
] as const;
export const STORY_GENRE_SCHEMA = z.enum(STORY_GENRES);

export const STORY_SUBGENRES = [
  "ancient_world",
  "body_horror",
  "classic_western",
  "closed_door_romance",
  "comedy_romance",
  "coming_of_age",
  "contemporary_romance",
  "cosy_mystery",
  "cosy_romance",
  "creature_horror",
  "cyberpunk",
  "dark_comedy",
  "dark_fantasy",
  "detective",
  "doll_horror",
  "dystopian",
  "early_modern",
  "erotic_romance",
  "everyday_life",
  "experimental",
  "exploration",
  "fairy_tale",
  "family_drama",
  "family_life",
  "first_contact",
  "forbidden_romance",
  "gothic_horror",
  "heist",
  "high_fantasy",
  "historical_romance",
  "intrigue",
  "legal_thriller",
  "magical_realism",
  "martial_arts",
  "medieval",
  "military_action",
  "mythic_fantasy",
  "noir",
  "organised_crime",
  "paranormal_fantasy",
  "parody",
  "police_procedural",
  "portal_fantasy",
  "post_apocalyptic",
  "psychological_horror",
  "psychological_thriller",
  "quest",
  "retold_book",
  "retold_manga",
  "retold_movie",
  "retold_myth",
  "retold_saga",
  "romantic_comedy",
  "romantic_fantasy",
  "satire",
  "school_life",
  "space_opera",
  "spy_action",
  "spy_thriller",
  "superhero",
  "supernatural_horror",
  "survival_adventure",
  "survival_thriller",
  "time_travel",
  "time_travel_fantasy",
  "tragedy",
  "treasure_hunt",
  "twentieth_century",
  "university_life",
  "urban_fantasy",
  "vacation",
  "victorian",
  "weird_western",
  "whodunit",
  "workplace",
  "world_war",
] as const;
export const STORY_SUBGENRE_SCHEMA = z.enum(STORY_SUBGENRES);

export const STORY_TROPES = [
  "amnesia",
  "chosen_one",
  "court_intrigue",
  "enemies_to_lovers",
  "ensemble_cast",
  "epistolary",
  "fake_relationship",
  "forbidden_love",
  "forced_proximity",
  "found_family",
  "friends_to_lovers",
  "friends_with_benefits",
  "grumpy_and_sunshine",
  "heist_crew",
  "hero_to_villain",
  "hidden_identity",
  "locked_room",
  "love_triangle",
  "mentor_and_student",
  "morally_grey_protagonist",
  "multiple_timelines",
  "quest_for_an_artefact",
  "redemption_arc",
  "rivals",
  "road_trip",
  "second_chance",
  "secret_heritage",
  "slow_burn",
  "time_loop",
  "unreliable_narrator",
  "villain_to_hero",
] as const;
export const STORY_TROPE_SCHEMA = z.enum(STORY_TROPES);

export const STORY_TENSES = ["mixed", "past", "present"] as const;
export const STORY_TENSE_SCHEMA = z.enum(STORY_TENSES);

export const STORY_PERSPECTIVES = [
  "first_person",
  "mixed",
  "second_person",
  "third_person_limited",
  "third_person_omniscient",
] as const;
export const STORY_PERSPECTIVE_SCHEMA = z.enum(STORY_PERSPECTIVES);

export const STORY_CONTENT_WARNINGS = [
  "abuse",
  "animal_cruelty",
  "death",
  "discrimination",
  "eating_disorder",
  "gore",
  "grief",
  "mental_illness",
  "pregnancy_loss",
  "self_harm",
  "sexual_content",
  "sexual_violence",
  "substance_abuse",
  "suicide",
  "violence",
  "war",
] as const;
export const STORY_CONTENT_WARNING_SCHEMA = z.enum(STORY_CONTENT_WARNINGS);

export const USER_IN_WRITING_GROUP_ROLES = [
  "administrator",
  "reader",
  "writer",
] as const;
export const USER_IN_WRITING_GROUP_ROLE_SCHEMA = z.enum(
  USER_IN_WRITING_GROUP_ROLES,
);

export const USER_IN_WRITING_GROUP_STATUSES = ["invited", "joined"] as const;
export const USER_IN_WRITING_GROUP_STATUS_SCHEMA = z.enum(
  USER_IN_WRITING_GROUP_STATUSES,
);

export const USER_IN_CHAT_GROUP_STATUSES = ["invited", "joined"] as const;
export const USER_IN_CHAT_GROUP_STATUS_SCHEMA = z.enum(
  USER_IN_CHAT_GROUP_STATUSES,
);

export const NOTIFICATION_TYPES = [
  "blind_date_ended",
  "blind_date_matched",
  "blind_date_reveal_requested",
  "invitation_accepted",
  "invited_to_chat_group",
  "invited_to_writing_group",
  "new_writing_post",
  "new_writing_thread",
  "role_changed_in_writing_group",
  "visibility_changed_in_writing_group",
] as const;
export const NOTIFICATION_TYPE_SCHEMA = z.enum(NOTIFICATION_TYPES);

export const USER_TOKEN_PURPOSES = [
  "account_deletion",
  "email_address_change",
  "email_address_verification",
  "password_reset",
] as const;
export const USER_TOKEN_PURPOSE_SCHEMA = z.enum(USER_TOKEN_PURPOSES);

export const STORY_IDEA_STATUSES = ["closed", "open"] as const;
export const STORY_IDEA_STATUS_SCHEMA = z.enum(STORY_IDEA_STATUSES);

export const STORY_IDEA_PARTY_SIZES = ["group", "one_on_one"] as const;
export const STORY_IDEA_PARTY_SIZE_SCHEMA = z.enum(STORY_IDEA_PARTY_SIZES);

export const PLATFORM_ROLES = ["administrator", "moderator"] as const;
export const PLATFORM_ROLE_SCHEMA = z.enum(PLATFORM_ROLES);

export const REPORT_TARGET_TYPES = [
  "chat_group",
  "chat_message",
  "forum_post",
  "story_idea",
  "user",
  "writing_group",
  "writing_post",
  "writing_thread",
] as const;
export const REPORT_TARGET_TYPE_SCHEMA = z.enum(REPORT_TARGET_TYPES);

export const REPORT_STATUSES = ["closed", "in_progress", "open"] as const;
export const REPORT_STATUS_SCHEMA = z.enum(REPORT_STATUSES);

export const REPORT_OUTCOMES = [
  "account_banned",
  "content_removed",
  "content_warning_added",
  "duplicate",
  "insufficient_information",
  "no_violation",
  "other",
  "target_gone",
  "warning_given",
] as const;
export const REPORT_OUTCOME_SCHEMA = z.enum(REPORT_OUTCOMES);

export const REPORT_CATEGORIES = [
  "harassment",
  "hate",
  "illegal_content",
  "legal_issue",
  "missing_content_warning",
  "other",
  "plagiarism",
  "self_harm",
  "sexual_content",
  "spam",
  "violence",
] as const;
export const REPORT_CATEGORY_SCHEMA = z.enum(REPORT_CATEGORIES);

export const AVATAR_ORIGINS = [
  "licence",
  "other",
  "own_work",
  "permission",
  "public_domain",
] as const;
export const AVATAR_ORIGIN_SCHEMA = z.enum(AVATAR_ORIGINS);

export const STRIKE_SEVERITIES = [
  "acceptable",
  "borderline",
  "severe",
] as const;
export const STRIKE_SEVERITY_SCHEMA = z.enum(STRIKE_SEVERITIES);

export const STRIKE_ACTIONS = ["deletion", "suspension", "warning"] as const;
export const STRIKE_ACTION_SCHEMA = z.enum(STRIKE_ACTIONS);

export const PROFILE_QUESTION_KINDS = ["choice", "text"] as const;
export const PROFILE_QUESTION_KIND_SCHEMA = z.enum(PROFILE_QUESTION_KINDS);

export const FORUM_VISIBILITIES = [
  "administration",
  "everyone",
  "members",
  "moderation",
] as const;
export const FORUM_VISIBILITY_SCHEMA = z.enum(FORUM_VISIBILITIES);

export const BLIND_DATE_WRITING_STYLES = ["asterisk", "prose"] as const;
export const BLIND_DATE_WRITING_STYLE_SCHEMA = z.enum(
  BLIND_DATE_WRITING_STYLES,
);

export const BLIND_DATE_POST_LENGTHS = ["long", "medium", "short"] as const;
export const BLIND_DATE_POST_LENGTH_SCHEMA = z.enum(BLIND_DATE_POST_LENGTHS);

export const BLIND_DATE_APPLICATION_STATUSES = [
  "declined",
  "expired",
  "matched",
  "pending",
  "withdrawn",
] as const;
export const BLIND_DATE_APPLICATION_STATUS_SCHEMA = z.enum(
  BLIND_DATE_APPLICATION_STATUSES,
);

export const BLIND_DATE_VERDICTS = ["no", "partly", "yes"] as const;
export const BLIND_DATE_VERDICT_SCHEMA = z.enum(BLIND_DATE_VERDICTS);

export const BLIND_DATE_AGAINS = ["maybe", "no", "yes"] as const;
export const BLIND_DATE_AGAIN_SCHEMA = z.enum(BLIND_DATE_AGAINS);

export const ACTIVITY_WINDOW_SCHEMA = z.object({
  userId: z.uuidv7(),
  windowStart: z.iso.datetime({ offset: true }),
});

export const BANNED_IP_SCHEMA = z.object({
  ipAddress: z.string(),
  bannedAt: z.iso.datetime({ offset: true }),
  bannedBy: z.uuidv7().nullable(),
  reason: z.string(),
});

export const BLIND_DATE_APPLICATION_SCHEMA = z.object({
  id: z.uuidv7(),
  userId: z.uuidv7(),
  status: BLIND_DATE_APPLICATION_STATUS_SCHEMA,
  offerId: z.uuidv7().nullable(),
  plotTitle: z.string(),
  writingStyle: BLIND_DATE_WRITING_STYLE_SCHEMA,
  postLength: BLIND_DATE_POST_LENGTH_SCHEMA,
  roleGender: z.string(),
  pairing: z.string(),
  note: z.string().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  decidedAt: z.iso.datetime({ offset: true }).nullable(),
  decidedBy: z.uuidv7().nullable(),
  decisionNote: z.string().nullable(),
});

export const BLIND_DATE_EXCLUSION_SCHEMA = z.object({
  userId: z.uuidv7(),
  reason: z.string(),
  addedBy: z.uuidv7().nullable(),
  addedAt: z.iso.datetime({ offset: true }),
});

export const BLIND_DATE_FEEDBACK_SCHEMA = z.object({
  id: z.uuidv7(),
  pairId: z.uuidv7(),
  userId: z.uuidv7(),
  worked: BLIND_DATE_VERDICT_SCHEMA.nullable(),
  again: BLIND_DATE_AGAIN_SCHEMA.nullable(),
  note: z.string().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const BLIND_DATE_NAME_SUSPICION_SCHEMA = z.object({
  id: z.uuidv7(),
  reportId: z.uuidv7(),
  pairId: z.uuidv7(),
  writingPostId: z.uuidv7().nullable(),
  suspectedId: z.uuidv7(),
  createdAt: z.iso.datetime({ offset: true }),
  resolvedAt: z.iso.datetime({ offset: true }).nullable(),
  resolvedBy: z.uuidv7().nullable(),
  confirmed: z.boolean().nullable(),
});

export const BLIND_DATE_OFFER_SCHEMA = z.object({
  id: z.uuidv7(),
  title: z.string(),
  description: z.string(),
  closedAt: z.iso.datetime({ offset: true }).nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  createdBy: z.uuidv7().nullable(),
  roles: z.array(z.string()),
  closesAt: z.iso.datetime({ offset: true }).nullable(),
});

export const BLIND_DATE_PAIR_SCHEMA = z.object({
  id: z.uuidv7(),
  writingGroupId: z.uuidv7(),
  matchedAt: z.iso.datetime({ offset: true }),
  matchedBy: z.uuidv7().nullable(),
  revealedAt: z.iso.datetime({ offset: true }).nullable(),
  rpgThreadId: z.uuidv7().nullable(),
  exchangeThreadId: z.uuidv7().nullable(),
  endedAt: z.iso.datetime({ offset: true }).nullable(),
  endedReason: z.string().nullable(),
  endedBy: z.uuidv7().nullable(),
});

export const BLIND_DATE_PARTNER_SCHEMA = z.object({
  pairId: z.uuidv7(),
  userId: z.uuidv7(),
  applicationId: z.uuidv7().nullable(),
  isActive: z.boolean(),
  wantsRevealAt: z.iso.datetime({ offset: true }).nullable(),
});

export const BLOCKED_EMAIL_DOMAIN_SCHEMA = z.object({
  domain: z.string(),
  addedBy: z.uuidv7().nullable(),
  addedAt: z.iso.datetime({ offset: true }),
  note: z.string().nullable(),
});

export const BLOCKED_WORD_SCHEMA = z.object({
  word: z.string(),
  addedBy: z.uuidv7().nullable(),
  addedAt: z.iso.datetime({ offset: true }),
  note: z.string().nullable(),
});

export const CHAT_GROUP_SCHEMA = z.object({
  id: z.uuidv7(),
  title: z.string(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
});

export const CHAT_MESSAGE_SCHEMA = z.object({
  id: z.uuidv7(),
  chatGroupId: z.uuidv7(),
  text: z.string(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const CUSTOM_PAGE_SCHEMA = z.object({
  slug: z.string(),
  title: z.string(),
  body: z.string(),
  isPublic: z.boolean(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
  lastEditedBy: z.uuidv7().nullable(),
});

export const FAVOURITE_SCHEMA = z.object({
  id: z.uuidv7(),
  userId: z.uuidv7(),
  writingGroupId: z.uuidv7().nullable(),
  writingThreadId: z.uuidv7().nullable(),
  writingPostId: z.uuidv7().nullable(),
  storyIdeaId: z.uuidv7().nullable(),
  chatGroupId: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  forumPostId: z.uuidv7().nullable(),
});

export const FORUM_CATEGORY_SCHEMA = z.object({
  id: z.uuidv7(),
  title: z.string(),
  position: int32,
  createdAt: z.iso.datetime({ offset: true }),
});

export const FORUM_POST_SCHEMA = z.object({
  id: z.uuidv7(),
  forumThreadId: z.uuidv7(),
  document: z.unknown(),
  text: z.string(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  editedAt: z.iso.datetime({ offset: true }).nullable(),
  editedBy: z.uuidv7().nullable(),
});

export const FORUM_THREAD_SCHEMA = z.object({
  id: z.uuidv7(),
  subForumId: z.uuidv7(),
  title: z.string(),
  visibility: FORUM_VISIBILITY_SCHEMA.nullable(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
});

export const NOTIFICATION_SCHEMA = z.object({
  id: z.uuidv7(),
  recipientId: z.uuidv7(),
  type: NOTIFICATION_TYPE_SCHEMA,
  actorId: z.uuidv7().nullable(),
  writingGroupId: z.uuidv7().nullable(),
  chatGroupId: z.uuidv7().nullable(),
  writingThreadId: z.uuidv7().nullable(),
  writingPostId: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  occurredAt: z.iso.datetime({ offset: true }),
  readAt: z.iso.datetime({ offset: true }).nullable(),
});

export const PROFILE_ANSWER_SCHEMA = z.object({
  userId: z.uuidv7(),
  questionId: z.uuidv7(),
  answerText: z.string().nullable(),
  optionId: z.uuidv7().nullable(),
});

export const PROFILE_QUESTION_SCHEMA = z.object({
  id: z.uuidv7(),
  section: z.string(),
  prompt: z.string(),
  kind: PROFILE_QUESTION_KIND_SCHEMA,
  position: int32,
});

export const PROFILE_QUESTION_OPTION_SCHEMA = z.object({
  id: z.uuidv7(),
  questionId: z.uuidv7(),
  label: z.string(),
  position: int32,
});

export const REPORT_SCHEMA = z.object({
  id: z.uuidv7(),
  reporterId: z.uuidv7().nullable(),
  targetType: REPORT_TARGET_TYPE_SCHEMA,
  reportedWritingGroupId: z.uuidv7().nullable(),
  reportedWritingThreadId: z.uuidv7().nullable(),
  reportedWritingPostId: z.uuidv7().nullable(),
  reportedStoryIdeaId: z.uuidv7().nullable(),
  reportedChatGroupId: z.uuidv7().nullable(),
  reportedChatMessageId: z.uuidv7().nullable(),
  reportedUserId: z.uuidv7().nullable(),
  reportedAuthorId: z.uuidv7().nullable(),
  targetExcerpt: z.string(),
  category: REPORT_CATEGORY_SCHEMA,
  reason: z.string(),
  createdAt: z.iso.datetime({ offset: true }),
  operatorId: z.uuidv7().nullable(),
  inProgressAt: z.iso.datetime({ offset: true }).nullable(),
  closedAt: z.iso.datetime({ offset: true }).nullable(),
  closingOutcome: REPORT_OUTCOME_SCHEMA.nullable(),
  closingNote: z.string().nullable(),
  status: REPORT_STATUS_SCHEMA,
  reportedForumPostId: z.uuidv7().nullable(),
});

export const STATUS_UPDATE_SCHEMA = z.object({
  id: z.uuidv7(),
  createdBy: z.uuidv7(),
  body: z.string(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const STATUS_UPDATE_COMMENT_SCHEMA = z.object({
  id: z.uuidv7(),
  statusUpdateId: z.uuidv7(),
  createdBy: z.uuidv7(),
  body: z.string(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const STORY_IDEA_SCHEMA = z.object({
  id: z.uuidv7(),
  title: z.string(),
  subtitle: z.string().nullable(),
  teaser: z.string(),
  synopsis: z.string(),
  genres: z.array(STORY_GENRE_SCHEMA),
  subgenres: z.array(STORY_SUBGENRE_SCHEMA),
  tropes: z.array(STORY_TROPE_SCHEMA),
  contentWarnings: z.array(STORY_CONTENT_WARNING_SCHEMA),
  storyThemes: z.string().nullable(),
  storySettings: z.string().nullable(),
  tense: STORY_TENSE_SCHEMA.nullable(),
  perspective: STORY_PERSPECTIVE_SCHEMA.nullable(),
  language: STORY_LANGUAGE_SCHEMA,
  lookingFor: z.string().nullable(),
  partySize: STORY_IDEA_PARTY_SIZE_SCHEMA.nullable(),
  status: STORY_IDEA_STATUS_SCHEMA,
  createdBy: z.uuidv7(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const STORY_IDEA_READER_SCHEMA = z.object({
  storyIdeaId: z.uuidv7(),
  userId: z.uuidv7(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const STRIKE_SCHEMA = z.object({
  id: z.uuidv7(),
  userId: z.uuidv7(),
  severity: STRIKE_SEVERITY_SCHEMA,
  action: STRIKE_ACTION_SCHEMA,
  reason: z.string(),
  suspendedUntil: z.iso.datetime({ offset: true }).nullable(),
  issuedBy: z.uuidv7().nullable(),
  issuedAt: z.iso.datetime({ offset: true }),
});

export const SUB_FORUM_SCHEMA = z.object({
  id: z.uuidv7(),
  categoryId: z.uuidv7(),
  title: z.string(),
  description: z.string(),
  visibility: FORUM_VISIBILITY_SCHEMA,
  position: int32,
  createdAt: z.iso.datetime({ offset: true }),
});

export const USER_SCHEMA = z.object({
  id: z.uuidv7(),
  username: z.string(),
  hashedPassword: z.string(),
  emailAddress: z.string(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
  emailAddressVerifiedAt: z.iso.datetime({ offset: true }).nullable(),
  platformRole: PLATFORM_ROLE_SCHEMA.nullable(),
  bannedAt: z.iso.datetime({ offset: true }).nullable(),
  bannedBy: z.uuidv7().nullable(),
  banReason: z.string().nullable(),
  aboutMe: z.string().nullable(),
  writingStyle: z.string().nullable(),
  postLength: z.string().nullable(),
  writingFrequency: z.string().nullable(),
  coWriterExpectations: z.string().nullable(),
  writingBoundaries: z.string().nullable(),
  genres: z.string().nullable(),
  suspendedUntil: z.iso.datetime({ offset: true }).nullable(),
  suspensionReason: z.string().nullable(),
  invitedBy: z.uuidv7().nullable(),
  isPrimordialAdmin: z.boolean(),
});

export const USER_AVATAR_SCHEMA = z.object({
  userId: z.uuidv7(),
  fileId: z.uuidv7(),
  origin: AVATAR_ORIGIN_SCHEMA,
  credit: z.string().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const USER_BLOCK_SCHEMA = z.object({
  blockerId: z.uuidv7(),
  blockedId: z.uuidv7(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const USER_IN_CHAT_GROUP_SCHEMA = z.object({
  userId: z.uuidv7(),
  chatGroupId: z.uuidv7(),
  status: USER_IN_CHAT_GROUP_STATUS_SCHEMA,
  invitedAt: z.iso.datetime({ offset: true }).nullable(),
  joinedAt: z.iso.datetime({ offset: true }).nullable(),
  lastReadAt: z.iso.datetime({ offset: true }).nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const USER_IN_WRITING_GROUP_SCHEMA = z.object({
  userId: z.uuidv7(),
  writingGroupId: z.uuidv7(),
  role: USER_IN_WRITING_GROUP_ROLE_SCHEMA,
  status: USER_IN_WRITING_GROUP_STATUS_SCHEMA,
  invitedAt: z.iso.datetime({ offset: true }).nullable(),
  joinedAt: z.iso.datetime({ offset: true }).nullable(),
  invitedBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const USER_SESSION_SCHEMA = z.object({
  id: z.uuidv7(),
  userId: z.uuidv7(),
  hashedToken: z.instanceof(Uint8Array),
  expiresAt: z.iso.datetime({ offset: true }),
  userAgent: z.string().nullable(),
  ipAddress: z.string().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});

export const USER_TOKEN_SCHEMA = z.object({
  id: z.uuidv7(),
  userId: z.uuidv7(),
  purpose: USER_TOKEN_PURPOSE_SCHEMA,
  hashedToken: z.instanceof(Uint8Array),
  expiresAt: z.iso.datetime({ offset: true }),
  consumedAt: z.iso.datetime({ offset: true }).nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  newEmailAddress: z.string().nullable(),
});

export const WATCHLIST_ENTRY_SCHEMA = z.object({
  userId: z.uuidv7(),
  note: z.string(),
  addedBy: z.uuidv7().nullable(),
  addedAt: z.iso.datetime({ offset: true }),
});

export const WRITING_GROUP_SCHEMA = z.object({
  id: z.uuidv7(),
  title: z.string(),
  subtitle: z.string().nullable(),
  synopsis: z.string(),
  visibility: WRITING_GROUP_VISIBILITY_SCHEMA,
  storyStatus: WRITING_GROUP_STORY_STATUS_SCHEMA,
  genres: z.array(STORY_GENRE_SCHEMA),
  subgenres: z.array(STORY_SUBGENRE_SCHEMA),
  tropes: z.array(STORY_TROPE_SCHEMA),
  contentWarnings: z.array(STORY_CONTENT_WARNING_SCHEMA),
  storyThemes: z.string().nullable(),
  storySettings: z.string().nullable(),
  tense: STORY_TENSE_SCHEMA.nullable(),
  perspective: STORY_PERSPECTIVE_SCHEMA.nullable(),
  language: STORY_LANGUAGE_SCHEMA,
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
  authorsArePseudonymous: z.boolean(),
});

export const WRITING_GROUP_NEXT_STEP_SCHEMA = z.object({
  id: z.uuidv7(),
  writingGroupId: z.uuidv7(),
  text: z.string(),
  createdBy: z.uuidv7().nullable(),
  completedAt: z.iso.datetime({ offset: true }).nullable(),
  completedBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
});

export const WRITING_POST_SCHEMA = z.object({
  id: z.uuidv7(),
  writingThreadId: z.uuidv7(),
  document: z.unknown(),
  text: z.string(),
  isDraft: z.boolean(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  editedAt: z.iso.datetime({ offset: true }).nullable(),
  editedBy: z.uuidv7().nullable(),
});

export const WRITING_THREAD_SCHEMA = z.object({
  id: z.uuidv7(),
  writingGroupId: z.uuidv7(),
  title: z.string(),
  createdBy: z.uuidv7().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  lastActivityAt: z.iso.datetime({ offset: true }),
});
